### PR TITLE
Added dean.txt

### PR DESCRIPTION
**Pull request by itzaadiiiii**

### CODE REVIEW

**Review by Aadiitya420 — CHANGES_REQUESTED** [review]
add one more line

**Comment by itzaadiiiii** [comment]
Okay

**Comment by itzaadiiiii** [comment]
added new in dean.txt

**Review by Aadiitya420 — APPROVED** [review]

**Comment by Aadiitya420** [comment]
Looks Good

**Review by Aadiitya420 — APPROVED** [review]

**Review by Aadiitya420 — COMMENTED** [review]
good Job folks

**Pull request merged**
